# <%= project['name'] %> Docker Container.
FROM <%= image['base'] %>
MAINTAINER <%= project['author']['name'] %> <<%= project['author']['email'] %>>

# Run some Debian packages installation.
ENV PACKAGES="php-pear curl"
RUN apt-get update && \
    apt-get install -yq --no-install-recommends $PACKAGES && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Run xdebug installation.
RUN curl -L http://pecl.php.net/get/xdebug-2.3.3.tgz >> /usr/src/php/ext/xdebug.tgz && \
    tar -xf /usr/src/php/ext/xdebug.tgz -C /usr/src/php/ext/ && \
    rm /usr/src/php/ext/xdebug.tgz && \
    docker-php-ext-install xdebug-2.3.3 && \
    docker-php-ext-install pcntl && \
    php -m

# Goto temporary directory.
WORKDIR /tmp

# Run composer and <%= project['code_name'] %> installation.
RUN composer selfupdate && \
    composer require "<%= project['code_name'] %>/<%= project['code_name'] %>:~<%= (version ? version : versions.first) %>" --prefer-source --no-interaction && \
    ln -s /tmp/vendor/bin/<%= project['code_name'] %> /usr/local/bin/<%= project['code_name'] %>

# Set up the application directory.
VOLUME ["/app"]
WORKDIR /app

# Set up the command arguments.
ENTRYPOINT ["/usr/local/bin/<%= project['code_name'] %>"]
CMD ["--help"]
