# {{ project.name }} Docker Container.
FROM {{ image.base }}
MAINTAINER {{ project.author.name }} <{{ project.author.email }}>

ENV PEAR_PACKAGES foo

WORKDIR /tmp

RUN apk --no-cache --repository http://dl-cdn.alpinelinux.org/alpine/edge/testing add \
        bash \
        ca-certificates \
        git \
        curl \
        unzip \
        php7 \
        php7-xml \
        php7-exif \
        php7-zip \
        php7-xmlreader \
        php7-zlib \
        php7-opcache \
        php7-mcrypt \
        php7-openssl \
        php7-curl \
        php7-json \
        php7-dom \
        php7-phar \
        php7-mbstring \
        php7-bcmath \
        php7-pdo \
        php7-pdo_pgsql \
        php7-pdo_sqlite \
        php7-pdo_mysql \
        php7-soap \
        php7-xdebug \
        php7-pcntl \
        php7-ctype \
        php7-session \
    && ln -s /usr/bin/php7 /usr/bin/php \
    && php -r "copy('https://pear.php.net/go-pear.phar', 'go-pear.phar');" \
    && php go-pear.phar \
    && php -r "unlink('go-pear.phar');" \
    && php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');" \
    && php composer-setup.php --install-dir=/usr/bin --filename=composer \
    && php -r "unlink('composer-setup.php');" \
    && composer require "{{ project.code_name }}/{{ project.code_name }}:~{{ versions.first }}" --prefer-source --no-interaction \
    && composer require "phpunit/php-invoker" --prefer-source --no-interaction \
    && ln -s /tmp/vendor/bin/{{ project.code_name }} /usr/local/bin/{{ project.code_name }} \
    && sed -i 's/nn and/nn, {{ project.author.name }} (Docker) and/g' /tmp/vendor/phpunit/phpunit/src/Runner/Version.php \

    # Enable X-Debug
    && sed -i 's/\;z/z/g' /etc/php7/conf.d/xdebug.ini \
    && php -m | grep -i xdebug

ONBUILD RUN [ $PEAR_PACKAGES != "foo" ] && pear install $PEAR_PACKAGES

VOLUME ["/app"]
WORKDIR /app

ENTRYPOINT ["/usr/local/bin/{{ project.code_name }}"]
CMD ["--help"]
