build:
	docker build --no-cache --rm -t julienbreux/{{ project.code_name }} master{% for version in versions %}
	docker build --no-cache --rm -t julienbreux/{{ project.code_name }}:{{ version }} {{ version }}{% endfor %}

version:
	docker run -t --rm julienbreux/{{ project.code_name }} --version{% for version in versions %}
	docker run -t --rm julienbreux/{{ project.code_name }}:{{ version }} --version{% endfor %}

debug:
	docker build --no-cache --rm -t julienbreux/phpunit master
	docker run -it --rm --entrypoint=/bin/bash julienbreux/phpunit

phpunit-test:
	cd test/ && docker run -v $(shell pwd)/test:/app --rm --entrypoint=/usr/bin/composer julienbreux/phpunit install
	docker run --rm --entrypoint=/usr/bin/php julienbreux/phpunit -v
	docker run --rm --entrypoint=/usr/local/bin/phpunit julienbreux/phpunit --version
	docker run -v $(shell pwd):/app  --rm julienbreux/phpunit --configuration='test/phpunit.xml' --coverage-text='test/coverage.txt'

.PHONY: build
